### ISSUE TITLE
QsPopupActivity visible in recents

### ISSUE THREAD

**Issue by swapnilkadlag** [msasikanth/pinnit#46] opened 2021-10-07 05:14 UTC
Upon opening the app from QsPopupActivity -> Open App, the QsPopupActivity is still visible in the recents, which I'm not sure if it is the intended behaviour or not.

**Comment by swapnilkadlag** [comment] 2021-10-07 05:26
If it is not the intended behaviour, please take a look at #47 which fixes it

**Comment by msasikanth** [comment] 2021-10-07 14:15
This is the intended behaviour of the app, closing the issue.

**Closed as completed by msasikanth** 2021-10-07 14:15 UTC
